# Generated by Django 4.0.1 on 2024-05-31 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('visit_date', models.DateField()),
                ('note', models.TextField(blank=True, null=True)),
                ('doctor_id', models.IntegerField()),
                ('room_id', models.IntegerField()),
            ],
        ),
    ]
