# Generated by Django 4.0.1 on 2024-06-01 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='note',
            new_name='reason',
        ),
    ]
