# Generated by Django 4.0.1 on 2024-05-30 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
