# Generated by Django 4.0.1 on 2024-05-31 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsuranceInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('date_issue', models.DateField()),
                ('expire_issue', models.DateField()),
                ('patient_record_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VisitHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('reason', models.CharField(max_length=255)),
                ('doctor_id', models.IntegerField()),
                ('result', models.TextField()),
                ('appointment_id', models.IntegerField()),
                ('invoice_id', models.IntegerField()),
                ('patient_record_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PatientRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.IntegerField()),
                ('insurance_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_record', to='patient_record.insuranceinformation')),
                ('visit_histories', models.ManyToManyField(related_name='patient_records', to='patient_record.VisitHistory')),
            ],
        ),
    ]
