# Generated by Django 4.0.1 on 2024-05-31 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_record', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insuranceinformation',
            name='patient_record_id',
        ),
    ]
