# Generated by Django 4.0.1 on 2024-05-31 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_bed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='bed_number',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
